### ISSUE TITLE
Signal 11 (Segmentation fault), address is 696e6144 from f7427d91

### ISSUE THREAD

**Issue by blackaslan** [ziggi/FCNPC#102]
Hi , i'm still looking for a fix please if anyone can help me would be nice:
```
 =========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 696e6144 from f7427d91

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0xdc) [0xf54a94cc]
  #1 in [0xf7790cb0]
  #2 in /lib32/libc.so.6(+0x75d91) [0xf7427d91]
  #3 in /lib32/libc.so.6(_IO_vfprintf+0x20dd) [0xf73f60fd]
  #4 in /lib32/libc.so.6(vsprintf+0x69) [0xf74123f9]
  #5 in /root/samp03/samp03svr() [0x80ad731]
  #6 in /root/samp03/samp03svr() [0x80d99e9]
  #7 in /root/samp03/samp03svr() [0x80950e4]
  #8 in plugins/crashdetect.so(_ZN11CrashDetect13DoAmxCallbackEiPiS0_+0x49b) [0xf738894b]
  #9 in plugins/crashdetect.so(+0x1b8f8) [0xf738b8f8]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.7.4

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```

Log's from crash detect: 
```
> [04:02:56] [debug] Server crashed due to an unknown error
[04:02:56] [debug] Native backtrace:
[04:02:56] [debug] #0 b7449e8b in _ZN10StackTraceC1EPv () from plugins/crashdetect.so
[04:02:56] [debug] #1 b7442bcf in _ZN11CrashDetect20PrintNativeBacktraceERSoPv () from plugins/crashdetect.so
[04:02:56] [debug] #2 b7443dbc in _ZN11CrashDetect20PrintNativeBacktraceEPv () from plugins/crashdetect.so
[04:02:56] [debug] #3 b7444226 in _ZN11CrashDetect11OnExceptionEPv () from plugins/crashdetect.so
[04:02:56] [debug] #4 b7449adc in ?? () from plugins/crashdetect.so
[04:02:56] [debug] #5 b77a1600 in __kernel_rt_sigreturn () from linux-gate.so.1
[04:02:56] [debug] #6 b77a1420 in __kernel_vsyscall () from linux-gate.so.1
[04:02:56] [debug] #7 b749c367 in gsignal () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
[04:02:56] [debug] #8 b749da23 in abort () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
[04:02:56] [debug] #9 b74da778 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
[04:02:56] [debug] #10 b74e07ea in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
[04:02:56] [debug] #11 b74e143d in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
[04:02:56] [debug] #12 b76c6e68 in _ZdlPv () from /usr/lib/i386-linux-gnu/libstdc++.so.6
[04:02:56] [debug] #13 0805fd0a in ?? () from samp03svr
[04:02:56] [debug] #14 0807f387 in ?? () from samp03svr
[04:02:56] [debug] #15 0807f4b4 in ?? () from samp03svr
[04:02:56] [debug] #16 080741c8 in ?? () from samp03svr
[04:02:56] [debug] #17 08074cb4 in ?? () from samp03svr
[04:02:56] [debug] #18 080763fe in ?? () from samp03svr
[04:02:56] [debug] #19 b7777ecb in ?? () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
[04:02:56] [debug] #20 b7559d0e in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
```
Here it's the code : 

````Pawn
stock crearZombies()
{
	new name[MAX_PLAYER_NAME + 1];
	for(new i = 0; i<MAX_ZOMBIES; i++)
	{
		format(name, sizeof(name), "Zombie_%d", i);
		crearZombie(name);

	}

}

stock crearZombie(name[])
{
	new npcid;
	npcid = FCNPC_Create(name);
	setZombieSpawn(npcid);
	FCNPC_SetHealth(npcid, zNPC_HEALTH); //variable vida de los zombies bot's
    //new Text3D:label = Create3DTextLabel("ZOMBIE", 0x008080FF, 30.0, 40.0, 50.0, 40.0, 0);
    //Attach3DTextLabelToPlayer(label, npcid , 0.0, 0.0, 0.7);
	crearBarraSalud(npcid);
    return 1;
}

stock destruirZombies()
{
	for(new i = 1; i<=MAX_ZOMBIES; i++)
	{
		borrarBarraSalud(i);
		FCNPC_Destroy(MAX_PLAYERS-i);
	}
}

stock setZombieSpawn(npcid)
{
	new masX;
	new masY;
	new Float:finalX;
	new Float:finalY;
	new Float:finalZ;
	new unBreak = 0;
	do
	{
		unBreak++;
		masX = random(2649);
		masY = random(1686);
		finalX = 160.1896 + masX;
		finalY = -962.9752 - masY;
		CA_FindZ_For2DCoord(finalX, finalY, finalZ);
	}
	while(finalZ < 0.001 && unBreak < 20);
	FCNPC_Spawn(npcid, skinsZombie[random(sizeof(skinsZombie))], finalX, finalY, finalZ+1.2);
	SetPlayerColor(npcid, ZOMBIE_COLOR);
	printf("Bot en %.2f, %.2f, %.2f", finalX, finalY, finalZ);
	
}

public FCNPC_OnSpawn(npcid)
{
    new
        Float:pos_x,
        Float:pos_y,
        Float:pos_z;

    FCNPC_GetPosition(npcid, pos_x, pos_y, pos_z);
    getMovementPosition(pos_x, pos_y, pos_z);

    FCNPC_GoTo(npcid, pos_x, pos_y, pos_z + 1.2, MOVE_TYPE_RUN, MOVE_SPEED_RUN);
}

public FCNPC_OnRespawn(npcid)
{
    new
        Float:pos_x,
        Float:pos_y,
        Float:pos_z;
	FCNPC_SetHealth(npcid, zNPC_HEALTH);
	actualizarBarraSalud(npcid);
	
	
	new masX;
	new masY;
	new Float:finalX;
	new Float:finalY;
	new Float:finalZ;
	new unBreak = 0;
	do
	{
		unBreak++;
		masX = random(2649);
		masY = random(1686);
		finalX = 160.1896 + masX;
		finalY = -962.9752 - masY;
		CA_FindZ_For2DCoord(finalX, finalY, finalZ);
	}
	while(finalZ < 0.001 && unBreak < 20);
	FCNPC_SetPosition(npcid, finalX, finalY, finalZ);
	printf("Bot en %.2f, %.2f, %.2f", finalX, finalY, finalZ);
	
    FCNPC_GetPosition(npcid, pos_x, pos_y, pos_z);
    getMovementPosition(pos_x, pos_y, pos_z);

    FCNPC_GoTo(npcid, pos_x, pos_y, pos_z + 1.2, MOVE_TYPE_RUN, MOVE_SPEED_RUN);
}




stock getMovementPosition(&Float:x, &Float:y, &Float:z)
{
	new Float:mX, Float:mY, Float:mZ;
	new cantidadAnadir;
	new Float:distanciaM;
	new posONeg;
	new unBreak = 0;
	do
	{
		unBreak++;
		if(posONeg == 1)
		{
			cantidadAnadir = random(50);
			mX = x + cantidadAnadir;
		}
		else
		{
			cantidadAnadir = random(50);
			mX = x - cantidadAnadir;
		}
		posONeg = random(2);
		if(posONeg == 1)
		{
			cantidadAnadir = random(50);
			mY = y + cantidadAnadir;
		}
		else
		{
			cantidadAnadir = random(50);
			mY = y - cantidadAnadir;
		}
		CA_FindZ_For2DCoord(mX, mY, mZ);
		distanciaM = floatsqroot( (z-mZ)*(z-mZ) );
	}
	while((mZ < 0.001 || distanciaM > 2.0) && unBreak < 20);
	x = mX;
	y = mY;
	z = mZ;
}



forward comprobarSeguimiento(npcid, playerid);
public comprobarSeguimiento(npcid, playerid)
{
	if(!FCNPC_IsValid(npcid))//if(!IsPlayerConnected(npcid))volver a la normalidad si crash continua
	{
		KillTimer(timerSiguiendo[npcid]);
		return 1;
	}
	new Float:finalX, Float:finalY, Float:finalZ;
	FCNPC_GetPosition(npcid, finalX, finalY, finalZ);
	if(!FCNPC_IsStreamedForAnyone(npcid))
	{
		zombieSiguiendo[npcid] = 0;
		KillTimer(timerSiguiendo[npcid]);
		FCNPC_Stop(npcid);
		FCNPC_StopAttack(npcid);
		getMovementPosition(finalX, finalY, finalZ);
		FCNPC_GoTo(npcid, finalX, finalY, finalZ+1.2, MOVE_TYPE_RUN, MOVE_SPEED_RUN);//MOVE_TYPE_XXX = XXX ( WALK, AUTO O RUN ) WALK DESPACIO AUTO MEDIO RUN CORRER  velocidad zombie bot
	}else{
		foreach(new i : Player)
		{
			if(FCNPC_IsStreamedIn(npcid, i) && GetPlayerTeam(i) == SOBREVIVIENTE)
			{
				if(IsPlayerInRangeOfPoint(i, zNPC_RANGO, finalX, finalY, finalZ)) //Distancia de deteccion en que el zombie bot te detecta
				{
					zombieSiguiendo[npcid] = 1;
					//FCNPC_MeleeAttack(npcid); devolver esto a la normalidad
					FCNPC_GoToPlayer(npcid, i);
					return 1;
				}
			}
		}
		zombieSiguiendo[npcid] = 0;
		KillTimer(timerSiguiendo[npcid]);
		FCNPC_Stop(npcid);
		FCNPC_StopAttack(npcid);
		getMovementPosition(finalX, finalY, finalZ);
		FCNPC_GoTo(npcid, finalX, finalY, finalZ+1.2, MOVE_TYPE_RUN, MOVE_SPEED_RUN); //MOVE_TYPE_XXX = XXX ( WALK, AUTO O RUN ) WALK DESPACIO AUTO MEDIO RUN CORRER  velocidad zombie bot
	}
	return 1;
}

public FCNPC_OnReachDestination(npcid)
{
	if(!IsPlayerConnected(npcid))
		return 1;
	new Float:finalX, Float:finalY, Float:finalZ;
	FCNPC_GetPosition(npcid, finalX, finalY, finalZ);
	if(zombieSiguiendo[npcid] == 0)
	{
		if(FCNPC_IsStreamedForAnyone(npcid))
		{
			foreach(new i : Player)
			{
				if(FCNPC_IsStreamedIn(npcid, i) && GetPlayerTeam(i) == SOBREVIVIENTE)
				{
					if(IsPlayerInRangeOfPoint(i, zNPC_RANGO, finalX, finalY, finalZ))//Distancia de deteccion en que el zombie bot te detecta
					{
						zombieSiguiendo[npcid] = 1;
					   FCNPC_MeleeAttack(npcid);
						FCNPC_GoToPlayer(npcid, i);
						if(timerSiguiendo[npcid] > 0)
							KillTimer(timerSiguiendo[npcid]);
						timerSiguiendo[npcid] = SetTimerEx("comprobarSeguimiento", 3000, true, "dd", npcid, i);
						return 1;
					}
				}
			}
		}
		getMovementPosition(finalX, finalY, finalZ);
		FCNPC_GoTo(npcid, finalX, finalY, finalZ+1.2, MOVE_TYPE_WALK, MOVE_SPEED_WALK); //MOVE_TYPE_XXX = XXX ( WALK, AUTO O RUN ) WALK DESPACIO AUTO MEDIO RUN CORRER  velocidad zombie bot
	}else{
		if(!FCNPC_IsStreamedForAnyone(npcid))
		{
			zombieSiguiendo[npcid] = 0;
			FCNPC_Stop(npcid);
			FCNPC_StopAttack(npcid);
			getMovementPosition(finalX, finalY, finalZ);
			FCNPC_GoTo(npcid, finalX, finalY, finalZ+1.2, MOVE_TYPE_RUN, MOVE_SPEED_RUN); //MOVE_TYPE_XXX = XXX ( WALK, AUTO O RUN ) WALK DESPACIO AUTO MEDIO RUN CORRER - velocidad zombie bot
		}else{
			foreach(new i : Player)
			{
				if(FCNPC_IsStreamedIn(npcid, i) && GetPlayerTeam(i) == SOBREVIVIENTE)
				{
					if(IsPlayerInRangeOfPoint(i, zNPC_RANGO, finalX, finalY, finalZ))//Distancia de deteccion en que el zombie bot te detecta
					{
						zombieSiguiendo[npcid] = 1;
						//FCNPC_MeleeAttack(npcid);
						FCNPC_GoToPlayer(npcid, i);
						return 1;
					}
				}
			}
			zombieSiguiendo[npcid] = 0;
			FCNPC_Stop(npcid);
			FCNPC_StopAttack(npcid);
			getMovementPosition(finalX, finalY, finalZ);
			FCNPC_GoTo(npcid, finalX, finalY, finalZ+1.2, MOVE_TYPE_RUN, MOVE_SPEED_RUN); //MOVE_TYPE_XXX = XXX ( WALK, AUTO O RUN ) WALK DESPACIO AUTO MEDIO RUN CORRER
		}
	}
	return 1;
}

public OnPlayerStreamIn(playerid, forplayerid)
{
	return 1;
}

public OnPlayerStreamOut(playerid, forplayerid)
{
	return 1;
}
public OnPlayerTakeDamage(playerid, issuerid, Float: amount, weaponid, bodypart)
{

	return 0;
}

public FCNPC_OnDeath(npcid, killerid, weaponid)
{
	if(GetPlayerTeam(killerid) == SOBREVIVIENTE)
	{
		darExperiencia(killerid, EXP_KILLZOMBI);
		pKills[killerid]++;
		cambiarTextoTextDraw(killerid, textKills{killerid}, "%s: %d", getMensaje(killerid, "KILLS"), pKills[killerid]);
		darDinero(killerid, 300);
        SendClientMessage(killerid, -1, "You have been awarded $300 for the kill.");
	}
	
	crearCadaverNPC(npcid);
	
	FCNPC_Respawn(npcid);
  
}

stock darDinero(playerid, cantidad)
{
	GivePlayerMoney(playerid, cantidad);
	//pDinero[playerid] += cantidad;
	cambiarTextoTextDraw(playerid, textDarDinero{playerid}, "+$%d", cantidad);
	PlayerTextDrawShow(playerid, textDarDinero{playerid});
	SetTimerEx("ocultarDarDinero", 2500, false, "d", playerid);
}

new Text3D:labelZombies[MAX_PLAYERS];

stock actualizarBarraSalud(npcid)
{
	static Float:saludZombie;
	static string[32];
	saludZombie = FCNPC_GetHealth(npcid);
	format(string, sizeof(string), "Zombie\n%.2f\tHP", saludZombie);
	Update3DTextLabelText(labelZombies[npcid], -1, string);
}

stock crearBarraSalud(npcid)
{
	static Float:saludZombie;
	static string[32];
	saludZombie = FCNPC_GetHealth(npcid);
	format(string, sizeof(string), "Zombie\n%.2f\tHP", saludZombie);
	labelZombies[npcid] = Create3DTextLabel(string, -1, 0, 0, 0, 100.0, 0, 1);
	Attach3DTextLabelToPlayer(labelZombies[npcid], npcid, 0, 0, 1.3);
}

stock borrarBarraSalud(npcid)
{
	Delete3DTextLabel(labelZombies[npcid]);
}

public FCNPC_OnTakeDamage(npcid, damagerid, weaponid, bodypart, Float:health_loss)
{
   if(IsPlayerNPC(damagerid) || GetPlayerTeam(damagerid) == ZOMBIE)
	//if(IsPlayerNPC(damagerid) || GetPlayerTeam(damagerid) == ZOMBIE)
		return 1;
	FCNPC_Stop(npcid);
	FCNPC_StopAttack(npcid);
	zombieSiguiendo[npcid] = 1;
	FCNPC_MeleeAttack(npcid);
	FCNPC_GoToPlayer(npcid, damagerid);
	if(timerSiguiendo[npcid] > 0)
		KillTimer(timerSiguiendo[npcid]);
	timerSiguiendo[npcid] = SetTimerEx("comprobarSeguimiento", 3000, true, "dd", npcid, damagerid);
	actualizarBarraSalud(npcid);
	return 1;
}

public FCNPC_OnGiveDamage(npcid, damagedid, weaponid, bodypart, Float:health_loss)
{
	if(IsPlayerNPC(damagedid))
		return 1;
	new Float:saludActual;
	GetPlayerHealth(damagedid, saludActual);
	saludActual = saludActual - (health_loss*zNPC_DANIO); // variable daño que hacen los zombies bot
    //FCNPC_SetHealth(damagedid, saludActual);
	SetPlayerHealth(damagedid, saludActual);
	return 1;
}
```
