### ISSUE TITLE
FCNPC crash when a player died.

### ISSUE THREAD

**Issue by JoaquinZc** [ziggi/FCNPC#138]
I have a problem. When a player dies, this fcnpc-crash error appears on the server and the server crashes.

fcnpc-crash:

```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 0 from f74eab86

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0xdc) [0xf5f2817c]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7795d50]
  #2 in /lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x83b86) [0xf74eab86]
  #3 in ./samp03svr() [0x80decd4]
  #4 in ./samp03svr() [0x80950e4]
  #5 in plugins/crashdetect.so(_ZN11CrashDetect17HandleAMXCallbackEiPiS0_+0x483) [0xf7437ad3]
  #6 in [0x1]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 1.8.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
