### ISSUE TITLE
FCNPC_Destroy crashes my server everytime.

### ISSUE THREAD

**Issue by r1ght00** [ziggi/FCNPC#154]
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 100007e from f25344a0

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0xdc) [0xf2526c9c]
  #1 in [0xf7f09cc0]
  #2 in plugins/FCNPC.so(_ZN7CServer17GetVehicleSeatPosEP8CVehicleh+0x20) [0xf25344a0]
  #3 in plugins/FCNPC.so(_ZN11CPlayerData7ProcessEv+0x7e7) [0xf2530dd7]
  #4 in plugins/FCNPC.so(_ZN14CPlayerManager7ProcessEv+0x42) [0xf2531a92]
  #5 in plugins/FCNPC.so(_ZN7CServer7ProcessEv+0x4f) [0xf253405f]
  #6 in plugins/FCNPC.so(ProcessTick+0x24) [0xf2535604]
  #7 in /root/ionic/samp03svr() [0x80d1ce2]
  #8 in /root/ionic/samp03svr() [0x80aef6c]
  #9 in /root/ionic/samp03svr() [0x80aa13a]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 1.8.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```

Pretty sure it's because FCNPC_Destroy because everytime I used this function,it crashed.
I tested myself with my job system which includes NPC and it destroy the NPC everytime they arrive at their location.

```
hook FCNPC_OnReachDest(npcid)
{
	foreach(new i : OjekPassengers)
	{
		if(OjekPassenger[i] == npcid)
		{
			FCNPC_Destroy(OjekPassenger[i]);
			Iter_SafeRemove(OjekPassengers, i, i);
			OjekPassenger[i] = -1;
			Log(log_callbacks, DEBUG, "Ojek onreachdest %d", i);
			return -2;
		}
	}
	return 1;
}
```

Server Version:0.3.7 R2-1
FCNPC Version: 1.8.2,compiled by myself.

**Comment by ziggi** [comment]
Where are you calsl `FCNPC_OnReachDest`?

**Comment by Fairuz-Afdhal** [comment]
There's no FCNPC_OnReachDest other than that except from my taxi job which should do the same.
I could give you my job system if you need.

**Comment by Fairuz-Afdhal** [comment]
Bump @ziggi

**Comment by NegativeIQ** [comment]
Can you load CrashDetect plugin to provide more info? (Load it before any other plugin just to be safe)

**Comment by Fairuz-Afdhal** [comment]
`plugins  crashdetect.so pawnraknet.so YSF.so SKY.so mysql.so sscanf.so streamer.so irc.so ctime.so DriftPointsCounter.so ColAndreas_static.so FCNPC.so log-plugin.so pawn-memory.so`
latest crash log from fcnpc log:
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 267c1791 from 814b7d9

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0xdc) [0xf250d17c]
  #1 in [0xf7ef9cc0]
  #2 in /root/ionic/samp03svr() [0x814b7d9]
  #3 in /root/ionic/samp03svr() [0x814cd5f]
  #4 in /root/ionic/samp03svr() [0x80af078]
  #5 in /root/ionic/samp03svr() [0x80aa13a]
  #6 in /lib32/libc.so.6(__libc_start_main+0xf6) [0xf7aa6986]
  #7 in /root/ionic/samp03svr() [0x804b4e1]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 1.8.0

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================

```

There isn't anything in server_log.txt..
