### ISSUE TITLE
Problem with created (0.3DL)

### ISSUE THREAD

**Issue by ZamekSG** [ziggi/FCNPC#175]
Hello, when i created NPC, i see this information in document FCNPC crash.

```
`=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 60dc from f7215965

Backtrace:
  #0 in plugins/FCNPC-DL.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf7205bc6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf77b2cc0]
  #2 in plugins/FCNPC-DL.so(_ZN11CWeaponInfo13GetReloadTimeEh+0x25) [0xf7215965]
  #3 in plugins/FCNPC-DL.so(_ZN11CPlayerData25GetWeaponActualReloadTimeEh+0x2d) [0xf720c2fd]
  #4 in plugins/FCNPC-DL.so(_ZN11CPlayerData7ProcessEv+0x5fb) [0xf721049b]
  #5 in plugins/FCNPC-DL.so(_ZN14CPlayerManager7ProcessEv+0x42) [0xf7212132]
  #6 in plugins/FCNPC-DL.so(_ZN7CServer7ProcessEv+0x54) [0xf7214654]
  #7 in plugins/FCNPC-DL.so(ProcessTick+0x23) [0xf7215f43]
  #8 in ./samp03svr() [0x80dd3d2]
  #9 in ./samp03svr() [0x80b7c1c]

Information:
  System: GNU/Linux
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.0

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80dc0b0
  FUNC_CPlayer__Kill: 0x80d5ac0
  FUNC_CPlayer__EnterVehicle: 0x80d6a70
  FUNC_CPlayer__ExitVehicle: 0x80d6bf0
  FUNC_CPlayer__SpawnForWorld: 0x80d7870
  FUNC_GetVehicleModelInfo: 0x80e14f0
  FUNC_CConsole__GetIntVariable: 0x80a87d0
  FUNC_ClientJoin_RPC: 0x80ba350

Pointers:
  VAR_ServerAuthentication: 0x81b7d2c
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================`
```
