### ISSUE TITLE
Crash when starting server-samp.exe (0.3DL)

### ISSUE THREAD

**Issue by Combat116** [ziggi/FCNPC#176]
```
=========================== FCNPC Exception Handler ============================
Address: 0xf957dca

Registers:
EAX: 0x724328 - EBX: 0x0 - ECX: 0x650076 - EDX: 0x0
ESI: 0x735910 - EDI: 0x735910 - EBP: 0x19fd44 - ESP: 0x19fcf8

Stack:
0x0: 0x2a8bb8a0 - 0x4: 0xf95859e - 0x8: 0x677d601d - 0xC: 0x22e4309c - 0x10: 0x724388 - 0x14: 0x72ec98
0x18: 0x735910 - 0x1C: 0x7358e0 - 0x20: 0x2a8bb8a0

Information:
  System: Windows
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.0

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466550
  FUNC_CPlayer__Kill: 0x485020
  FUNC_CPlayer__EnterVehicle: 0x485670
  FUNC_CPlayer__ExitVehicle: 0x485790
  FUNC_CPlayer__SpawnForWorld: 0x487730
  FUNC_GetVehicleModelInfo: 0x4892a0
  FUNC_CConsole__GetIntVariable: 0x490c80
  FUNC_ClientJoin_RPC: 0x497ef0

Pointers:
  VAR_ServerAuthentication: 0x4fc470
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5

Callbacks:
  FUNC_CGameMode__OnPlayerGiveDamage: 0x46f050
  FUNC_CGameMode__OnPlayerTakeDamage: 0x46efd0
  FUNC_CGameMode__OnPlayerWeaponShot: 0x46f640
  FUNC_CGameMode__OnPlayerStreamIn: 0x46ebc0
  FUNC_CGameMode__OnPlayerStreamOut: 0x46ec30
  FUNC_CGameMode__OnGameModeExit: 0x46da90
=========================== FCNPC Exception Handler ============================
```
