### ISSUE TITLE
FCNPC Exception Handler

### ISSUE THREAD

**Issue by MateusArthur** [ziggi/FCNPC#183]
when the server gets a good time on (about 24 hours), the server crash
```
Signal 11 (Segmentation fault), address is 8 from b70078d1

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xb6ffca36]
  #1 in [0xb77a6600]
  #2 in plugins/FCNPC.so(_ZN11CPlayerData7ProcessEv+0xca1) [0xb70078d1]
  #3 in plugins/FCNPC.so(_ZN14CPlayerManager7ProcessEv+0x42) [0xb7008ec2]
  #4 in plugins/FCNPC.so(_ZN7CServer7ProcessEv+0x54) [0xb700b3e4]
  #5 in plugins/FCNPC.so(ProcessTick+0x23) [0xb700ccc3]
  #6 in ./samp03svr() [0x80d1ce2]
  #7 in ./samp03svr() [0x80aef3a]
  #8 in ./samp03svr() [0x80aa13a]
  #9 in /lib32/libc.so.6(__libc_start_main+0xf7) [0xb73f7637]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.0

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
