### ISSUE TITLE
Crash: Signal 11 (Segmentation fault), address is 73c0 from f7c9dc72

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#198]
What's the problem?

```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 73c0 from f7c9dc72

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0xdc) [0xf69c30cc]
  #1 in [0xf7f6ebd0]
  #2 in /lib/i386-linux-gnu/libc.so.6(+0x8dc72) [0xf7c9dc72]
  #3 in ./samp03svr() [0x80eb3fc]
  #4 in ./samp03svr() [0x80950e4]
  #5 in plugins/crashdetect.so(_ZN18CrashDetectHandler15ProcessCallbackEiPiS0_+0x4bb) [0xf7be0b9b]
  #6 in plugins/crashdetect.so(+0x1cfc2) [0xf7be4fc2]
  #7 in plugins/crashdetect.so(amx_Exec+0xdc7) [0xf7be9bc7]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 1.8.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5e00
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81ab8ec
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
