### ISSUE TITLE
Crash with YSF

### ISSUE THREAD

**Issue by iMarllun** [ziggi/FCNPC#212]
Plugins: crashdetect YSF streamer sscanf pawncmd mysql discord-connector FCNPC
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 2599c from f725f9d4

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf3761a36]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7726cb0]
  #2 in plugins/YSF.so(_Z17IsPlayerConnectedi+0x24) [0xf725f9d4]
  #3 in plugins/YSF.so(_ZN7CPlugin14GetPlayerCountEv+0x5f) [0xf72171df]
  #4 in plugins/YSF.so(_Z23HOOK_ProcessQueryPacketjtPcii+0x371) [0xf722c831]
  #5 in ./samp03svr() [0x808ebdb]
  #6 in ./samp03svr() [0x8074846]
  #7 in ./samp03svr() [0x80763fe]
  #8 in /lib/i386-linux-gnu/libpthread.so.0(+0x627a) [0xf76fe27a]
  #9 in /lib/i386-linux-gnu/libc.so.6(clone+0x66) [0xf743b366]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.0

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
