### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by iMarllun** [ziggi/FCNPC#222]
is closing the server on debian 9, in debian 10 did not happen
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is e79 from 80988f1

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0xdc) [0xb735617c]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xb7764600]
  #2 in ./samp03svr() [0x80988f1]
  #3 in ./samp03svr() [0x80a5563]
  #4 in ./samp03svr() [0x80b081b]
  #5 in ./samp03svr() [0x8071d38]
  #6 in ./samp03svr() [0x8071e32]
  #7 in ./samp03svr() [0x807bc50]
  #8 in ./samp03svr() [0x80aed3d]
  #9 in ./samp03svr() [0x80aef02]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 1.8.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
