### ISSUE TITLE
Crash FCNPC_EnterVehicle

### ISSUE THREAD

**Issue by iMarllun** [ziggi/FCNPC#227]
Plugins: crashdetect- last version FCNPC - last version streamer- last version sscanf - last version pawncmd - last version mysql - last version

pawncc version 3.10.10

when i use this function the server shuts down. in FCNPC 1.8.2 this crash doesn't happen

```pawn
FCNPC_EnterVehicle(npcid, vehicleid, seatid, type = MOVE_TYPE_WALK)
```
```
=========================== FCNPC Exception Handler ============================
Address: 0x171

Registers:
EAX: 0x1 - EBX: 0x1 - ECX: 0x19fe8c - EDX: 0x64
ESI: 0x9233864 - EDI: 0x7b9210 - EBP: 0x19fdac - ESP: 0x19fdb0

Stack:
0x0: 0x6351b9dd - 0x4: 0x2f7e168 - 0x8: 0x171 - 0xC: 0x1 - 0x10: 0x0 - 0x14: 0x5cb9b20
0x18: 0x44e50f7b - 0x1C: 0xc4da47f0 - 0x20: 0x41595df3

Information:
  System: Windows
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.0 //Is 2.0.0 or 2.0.1?

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466570
  FUNC_CPlayer__Kill: 0x484620
  FUNC_CPlayer__EnterVehicle: 0x484c72
  FUNC_CPlayer__ExitVehicle: 0x484f52
  FUNC_CPlayer__SpawnForWorld: 0x486d30
  FUNC_GetVehicleModelInfo: 0x488240
  FUNC_CConsole__GetIntVariable: 0x48b5b0
  FUNC_ClientJoin_RPC: 0x4918f0

Pointers:
  VAR_ServerAuthentication: 0x4f5fe8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5

Callbacks:
  FUNC_CGameMode__OnPlayerGiveDamage: 0x46ed70
  FUNC_CGameMode__OnPlayerTakeDamage: 0x46ecf0
  FUNC_CGameMode__OnPlayerWeaponShot: 0x46f360
  FUNC_CGameMode__OnPlayerStreamIn: 0x46e8e0
  FUNC_CGameMode__OnPlayerStreamOut: 0x46e950
  FUNC_CGameMode__OnGameModeExit: 0x46d7b0
=========================== FCNPC Exception Handler ============================
```
also, with the latest version of the plugin is returning this warning

*** [FCNPC] Info: A newer version (v2.0.1) is available at https://github.com/ziggi/FCNPC/releases ***
