### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fergus-pwn** [ziggi/FCNPC#245]
how to fix it?
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 2a from 809568c

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf5464706]
  #1 in [0xf77a5410]
  #2 in ./samp03svr() [0x809568c]
  #3 in ./samp03svr() [0x80957cd]
  #4 in plugins/streamer.so(+0x4008e) [0xf5a7a08e]
  #5 in ./samp03svr() [0x80ea3b1]
  #6 in ./samp03svr() [0x80aefc2]
  #7 in ./samp03svr() [0x80aa13a]
  #8 in /lib/libc.so.6(__libc_start_main+0xf3) [0xf748e933]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.3

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
