### ISSUE TITLE
Backtrace FCNPC crash:  in plugins/FCNPC.so

### ISSUE THREAD

**Issue by truenospawnscript** [ziggi/FCNPC#265]
I have a problem, it turns out that I am using the FCNPC plugin to load the npc of my server but I have no idea why it crashes, could you tell me the solution to the problem? I would appreciate it thanks..
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is f54d2010 from f666ed4f

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf66516e6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7f6bb40]
  #2 in plugins/FCNPC.so(_ZN12MapWaterMeshD1Ev+0xf) [0xf666ed4f]
  #3 in plugins/FCNPC.so(_ZN15ColAndreasWorldD1Ev+0x9a) [0xf667632a]
  #4 in plugins/FCNPC.so(_ZN7CServerD1Ev+0x15b) [0xf6660a7b]
  #5 in plugins/FCNPC.so(Unload+0x2e) [0xf666188e]
  #6 in /home/tcagame/truenos/4/samp03svr() [0x80d210b]
  #7 in /home/tcagame/truenos/4/samp03svr() [0x80aa237]
  #8 in /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7ad0b41]
  #9 in /home/tcagame/truenos/4/samp03svr() [0x804b4e1]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.4

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
