### ISSUE TITLE
Signal 11 (Segmentation fault), address is 94 from 8096232

### ISSUE THREAD

**Issue by dXl-lll** [ziggi/FCNPC#287]
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 94 from 8096232

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf26626e6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7ed6570]
  #2 in ./samp03svr() [0x8096232]
  #3 in plugins/deadlinevoice.so(_ZN4Pawn32OnPlayerActivationKeyPressForAllEth+0x7a) [0xf64d8b3a]
  #4 in [0x45d0db00]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.4

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
