### ISSUE TITLE
Linux Server Crash

### ISSUE THREAD

**Issue by Revalto** [ziggi/FCNPC#292]
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 4725eb4d from f77814a8

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf77726e6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7f6c570]
  #2 in plugins/FCNPC.so(_ZN7CServer24IsMovePathfindingEnabledEi+0x8) [0xf77814a8]
  #3 in plugins/FCNPC.so(_ZN11CPlayerData18SetMovePathfindingEi+0x2d) [0xf777dcfd]
  #4 in plugins/FCNPC.so(_ZN11CPlayerData4GoToERK7CVectoriiifbffj+0x1ca) [0xf777df5a]
  #5 in plugins/FCNPC.so(_ZN8CNatives10FCNPC_GoToEP6tagAMXPi+0x11f) [0xf7785a5f]
  #6 in ./samp-srv() [0x80950e4]
  #7 in plugins/crashdetect.so(_ZN11CrashDetect10OnCallbackEiPiS0_+0x478) [0xf792d168]
  #8 in plugins/crashdetect.so(+0x202ab) [0xf79302ab]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.5

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
