### ISSUE TITLE
Signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by PMEMOREX** [ziggi/FCNPC#301]
Hello, I get this error when I start the server on ubuntu, also the server won't start.

```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 0 from f5ac8365

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf5a9cba6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7f61570]
  #2 in plugins/FCNPC.so(subhook_new+0x75) [0xf5ac8365]
  #3 in plugins/FCNPC.so(_ZN6CHooks12InstallHooksEv+0x31) [0xf5a9f921]
  #4 in plugins/FCNPC.so(_ZN7CServer10InitializeEv+0x34) [0xf5aabcf4]
  #5 in plugins/FCNPC.so(AmxLoad+0x123) [0xf5aacf13]
  #6 in ./samp03svr() [0x80d17f9]
  #7 in ./samp03svr() [0x80a4daf]
  #8 in ./samp03svr() [0x80ab642]
  #9 in ./samp03svr() [0x80a9e5d]

Information:
  System: GNU/Linux
  SA-MP: Unknown
  FCNPC: 2.0.8

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0600
  FUNC_CPlayer__Kill: 0x80cadb0
  FUNC_CPlayer__EnterVehicle: 0x80cbd50
  FUNC_CPlayer__ExitVehicle: 0x80cbed0
  FUNC_CPlayer__SpawnForWorld: 0x80ccb50
  FUNC_GetVehicleModelInfo: 0x80d58a0
  FUNC_CConsole__GetIntVariable: 0x80a0040
  FUNC_ClientJoin_RPC: 0x80afcf0

Pointers:
  VAR_ServerAuthentication: 0x81a06e8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
