### ISSUE TITLE
FCNPC CRASH

### ISSUE THREAD

**Issue by zubarer** [ziggi/FCNPC#308]
Привет, как исправить краш?

```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 20 from 809568c

Backtrace:
  #0 in plugins/FCNPC.so(_ZN15uyvefmcd2DkAeM9PLPWKtcPjpxQzc26CxTtPFuQMNfm2RfEHfKinfo_tPv+0x126) [0xf5d07ba6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7f77dc0]
  #2 in ./samp03svr() [0x809568c]
  #3 in ./samp03svr() [0x80957cd]
  #4 in plugins/fmt.so(+0xbd33) [0xf7a28d33]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.8

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```

**Comment by ziggi** [comment]
Не знаю, тут что-то  с fmt.so

**Comment by zubarer** [comment]
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 0 from f5d1417e

Backtrace:
  #0 in plugins/FCNPC.so(_ZN15uyvefmcd2DkAeM9PLPWKtcPjpxQzc26CxTtPFuQMNfm2RfEHfKinfo_tPv+0x126) [0xf5d07ba6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7fcbdc0]
  #2 in plugins/FCNPC.so(_ZN14CPlayerManager7ProcessEv+0x1e) [0xf5d1417e]
  #3 in plugins/FCNPC.so(_ZN7CServer7ProcessEv+0x54) [0xf5d16704]
  #4 in plugins/FCNPC.so(ProcessTick+0x23) [0xf5d17ff3]
  #5 in ./samp03svr() [0x80d1852]
  #6 in ./samp03svr() [0x80aec2c]
  #7 in ./samp03svr() [0x80a9e9a]
  #8 in /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0x106) [0xf7adde46]
  #9 in ./samp03svr() [0x804b4e1]

Information:
  System: GNU/Linux
  SA-MP: Unknown
  FCNPC: 2.0.8

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x0
  FUNC_CPlayer__Kill: 0x0
  FUNC_CPlayer__EnterVehicle: 0x0
  FUNC_CPlayer__ExitVehicle: 0x0
  FUNC_CPlayer__SpawnForWorld: 0x0
  FUNC_GetVehicleModelInfo: 0x0
  FUNC_CConsole__GetIntVariable: 0x0
  FUNC_ClientJoin_RPC: 0x0

Pointers:
  VAR_ServerAuthentication: 0x0
  VAR_NetVersion: 0x0

Offsets:
  OFFSET_RemoteSystemManager: 0x0
  OFFSET_RemoteSystemSize: 0x0
  OFFSET_RemoteSystem__ConnectMode: 0x0
  OFFSET_RemoteSystem__Unknown: 0x0
=========================== FCNPC Exception Handler ============================
```

а тут?

**Comment by ziggi** [comment]
Тут что-то с определением версии SA-MP. FCNPC работает только на 0.3.7 R2, 0.3.7 R3 и 0.3.DL

**Comment by zubarer** [comment]
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 1030 from 80a1145

Backtrace:
  #0 in plugins/FCNPC.so(_ZN15uyvefmcd2DkAeM9PLPWKtcPjpxQzc26CxTtPFuQMNfm2RfEHfKinfo_tPv+0x126) [0xf5d07ba6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7f6ddc0]
  #2 in ./samp03svr() [0x80a1145]
  #3 in ./samp03svr() [0x80ab601]
  #4 in ./samp03svr() [0x80aba0b]
  #5 in ./samp03svr() [0x80aa0fd]
  #6 in /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0x106) [0xf7a7fe46]
  #7 in ./samp03svr() [0x804b4e1]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.8

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x0
  FUNC_CPlayer__Kill: 0x0
  FUNC_CPlayer__EnterVehicle: 0x0
  FUNC_CPlayer__ExitVehicle: 0x0
  FUNC_CPlayer__SpawnForWorld: 0x0
  FUNC_GetVehicleModelInfo: 0x0
  FUNC_CConsole__GetIntVariable: 0x0
  FUNC_ClientJoin_RPC: 0x0

Pointers:
  VAR_ServerAuthentication: 0x0
  VAR_NetVersion: 0x0

Offsets:
  OFFSET_RemoteSystemManager: 0x0
  OFFSET_RemoteSystemSize: 0x0
  OFFSET_RemoteSystem__ConnectMode: 0x0
  OFFSET_RemoteSystem__Unknown: 0x0
=========================== FCNPC Exception Handler ============================
```

а теперь? версия определяется, но все равно краш
