### ISSUE TITLE
Server crashes randomly (FCNPC 2.0.9, SA:MP 0.3.7 R2, Ubuntu 22.04).

### ISSUE THREAD

**Issue by TyAmosMoses** [ziggi/FCNPC#317]
**Describe the bug**
My server crashes randomly for no reason. CrashDetect doesn't say anything, I've already set other plugins. I'm starting to think it's FCNPC (it's also the only one that leaves logs).

**To Reproduce**
There is no way to reproduce it, it happens randomly

**FCNPC Log**
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 58 from f3ee0e33

Backtrace:
  #0 in plugins/fcnpc-209.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf3c77ba6]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf47905a0]
  #2 in plugins/raknet.so(_ZN6Script10ExecPublicERKSt10shared_ptrIN3ptl6PublicEEihP9BitStream+0x23) [0xf3ee0e33]
  #3 in plugins/raknet.so(_ZNSt17_Function_handlerIFbRKSt10shared_ptrI6ScriptEEZN6Plugin7OnEventIL12PR_EventType4EEEbihP9BitStreamEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_+0x38) [0xf3eeb2a8]
  #4 in plugins/raknet.so(_ZN14MessageHandler9OnReceiveEP16RakPeerInterfaceP6Packet+0x17c) [0xf3ee816c]
  #5 in ./samp03svr() [0x806f969]
  #6 in ./samp03svr() [0x8071d73]
  #7 in ./samp03svr() [0x807bc50]
  #8 in plugins/raknet.so(_ZN5Hooks18RakServer__ReceiveEPv+0xa2) [0xf3ee7442]
  #9 in ./samp03svr() [0x80aed3d]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.9

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5e00
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81ab8ec
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```

**Versions:**
 - OS: Ubuntu 22.04
 - SA-MP version: 0.3.7 R2
 - FCNPC version: 2.0.9
 

I'm dealing with this error for months now. From time to time my server goes down. I use the latest version of FCNPC and my plugins are:

discordconnector, gps, PawnRakNet, PawnCMD, streamer sscanf, bcrypt mysql
