### ISSUE TITLE
FCNPC CRASHES

### ISSUE THREAD

**Issue by globrm** [ziggi/FCNPC#321]
Hello guys.
Any ideas on what's causing this?
Address: 0x77584f24 | Address: 0x49df95| Address: 0x20aa34e7

=========================== FCNPC Exception Handler ============================
Address: **0x77584f24**

Registers:
EAX: 0x19e5ec - EBX: 0xb40000 - ECX: 0x160 - EDX: 0x0
ESI: 0x160 - EDI: 0x0 - EBP: 0x19e5c0 - ESP: 0x19e580

Stack:
0x0: 0x4c5c90 - 0x4: 0x160 - 0x8: 0x19fb0c - 0xC: 0x0 - 0x10: 0x0 - 0x14: 0x160
0x18: 0x0 - 0x1C: 0x0 - 0x20: 0x38340000

Information:
  System: Windows
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.10

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466550
  FUNC_CPlayer__Kill: 0x485020
  FUNC_CPlayer__EnterVehicle: 0x485670
  FUNC_CPlayer__ExitVehicle: 0x485790
  FUNC_CPlayer__SpawnForWorld: 0x487730
  FUNC_GetVehicleModelInfo: 0x4892a0
  FUNC_CConsole__GetIntVariable: 0x490c80
  FUNC_ClientJoin_RPC: 0x497ef0

Pointers:
  VAR_ServerAuthentication: 0x4fc470
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5

Callbacks:
  FUNC_CGameMode__OnPlayerGiveDamage: 0x46f050
  FUNC_CGameMode__OnPlayerTakeDamage: 0x46efd0
  FUNC_CGameMode__OnPlayerWeaponShot: 0x46f640
  FUNC_CGameMode__OnPlayerStreamIn: 0x46ebc0
  FUNC_CGameMode__OnPlayerStreamOut: 0x46ec30
  FUNC_CGameMode__OnGameModeExit: 0x46da90
=========================== FCNPC Exception Handler ============================

OR this

=========================== FCNPC Exception Handler ============================
Address: **0x49df95**

Registers:
EAX: 0x0 - EBX: 0x8 - ECX: 0x0 - EDX: 0x64e509e8
ESI: 0x1 - EDI: 0x19f0f0 - EBP: 0x64e50b38 - ESP: 0x19f0bc

Stack:
0x0: 0x0 - 0x4: 0x64e509e8 - 0x8: 0x19f280 - 0xC: 0x12b - 0x10: 0x2 - 0x14: 0x64e509e8
0x18: 0x49e243 - 0x1C: 0x0 - 0x20: 0x1

Information:
  System: Windows
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.10

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466550
  FUNC_CPlayer__Kill: 0x485020
  FUNC_CPlayer__EnterVehicle: 0x485670
  FUNC_CPlayer__ExitVehicle: 0x485790
  FUNC_CPlayer__SpawnForWorld: 0x487730
  FUNC_GetVehicleModelInfo: 0x4892a0
  FUNC_CConsole__GetIntVariable: 0x490c80
  FUNC_ClientJoin_RPC: 0x497ef0

Pointers:
  VAR_ServerAuthentication: 0x4fc470
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5

Callbacks:
  FUNC_CGameMode__OnPlayerGiveDamage: 0x46f050
  FUNC_CGameMode__OnPlayerTakeDamage: 0x46efd0
  FUNC_CGameMode__OnPlayerWeaponShot: 0x46f640
  FUNC_CGameMode__OnPlayerStreamIn: 0x46ebc0
  FUNC_CGameMode__OnPlayerStreamOut: 0x46ec30
  FUNC_CGameMode__OnGameModeExit: 0x46da90
=========================== FCNPC Exception Handler ============================

=========================== FCNPC Exception Handler ============================
Address: **0x20aa34e7**

Registers:
EAX: 0x0 - EBX: 0x0 - ECX: 0x80e8 - EDX: 0x3a4b9fd8
ESI: 0x25d84 - EDI: 0x0 - EBP: 0x3e8 - ESP: 0x2152ef00

Stack:
0x0: 0xf - 0x4: 0x17 - 0x8: 0x2152efe0 - 0xC: 0x11 - 0x10: 0x80e8 - 0x14: 0x3a4b9fd8
0x18: 0x20ab016a - 0x1C: 0x2152ef88 - 0x20: 0x20b77cf0

Information:
  System: Windows
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.10

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466550
  FUNC_CPlayer__Kill: 0x485020
  FUNC_CPlayer__EnterVehicle: 0x485670
  FUNC_CPlayer__ExitVehicle: 0x485790
  FUNC_CPlayer__SpawnForWorld: 0x487730
  FUNC_GetVehicleModelInfo: 0x4892a0
  FUNC_CConsole__GetIntVariable: 0x490c80
  FUNC_ClientJoin_RPC: 0x497ef0

Pointers:
  VAR_ServerAuthentication: 0x4fc470
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5

Callbacks:
  FUNC_CGameMode__OnPlayerGiveDamage: 0x46f050
  FUNC_CGameMode__OnPlayerTakeDamage: 0x46efd0
  FUNC_CGameMode__OnPlayerWeaponShot: 0x46f640
  FUNC_CGameMode__OnPlayerStreamIn: 0x46ebc0
  FUNC_CGameMode__OnPlayerStreamOut: 0x46ec30
  FUNC_CGameMode__OnGameModeExit: 0x46da90
=========================== FCNPC Exception Handler ============================

Thanks in advanced <3

**Comment by recepilhanli** [comment]
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is fff5b000 from ef369371

Backtrace:
  #0 in plugins/FCNPC-DL.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xed78ad16]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xef72e5a0]
  #2 in /lib/i386-linux-gnu/libc.so.6(+0x146371) [0xef369371]
  #3 in [0x804cf0a]
  #4 in [0x807a35b]
  #5 in [(nil)]

Information:
  System: GNU/Linux
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.8

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80dc0b0
  FUNC_CPlayer__Kill: 0x80d5ac0
  FUNC_CPlayer__EnterVehicle: 0x80d6a70
  FUNC_CPlayer__ExitVehicle: 0x80d6bf0
  FUNC_CPlayer__SpawnForWorld: 0x80d7870
  FUNC_GetVehicleModelInfo: 0x80e14f0
  FUNC_CConsole__GetIntVariable: 0x80a87d0
  FUNC_ClientJoin_RPC: 0x80ba350

Pointers:
  VAR_ServerAuthentication: 0x81b7d2c
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================

Same here, I've been using these plugins for years, and it's the first time I've seen this.

**Comment by itslapsu** [comment]
And my crash))

=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 18 from 80961fc

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf5a9bb86]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7eda580]
  #2 in ./samp03svr() [0x80961fc]
  #3 in plugins/FCNPC.so(amx_Push+0x29) [0xf5ac5eb9]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.11

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5e00
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81ab8ec
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================

**Comment by itslapsu** [comment]
> 0x80961fc

The problem is that it is not clear why. Everything is going normally and then the server just crashes. And the NPCs are just standing in place.

**Comment by itslapsu** [comment]
`if ( GetPVarInt( i, "Whore:Active" ) && Player[i][uWhoreTimeEnd] )
		{
			if( Player[i][uWhoreTimeEnd] == 1 )
			{
				new whore = GetPVarInt( i, "Whore:Active" ) - 1;

				FCNPC_SetVirtualWorld( CrimeWhore[whore][ w_npc ], 1 );

				RespawnWhore( whore );

				FCNPC_SetInvulnerable( CrimeWhore[whore][ w_npc ], true );

				CrimeWhore[whore][ w_in_progress ] = false;

				DeletePVar( i, "Whore:Active" );
				DeletePVar( i, "Whore:Sit" );

				if( GetPVarInt( i, "Whore:CheckpointDevlivery" ) ) DisablePlayerRaceCheckpoint(i);

				SendClient:( i, C_WHITE, ""gbError"Вы не смогли доставить проститутку в обозначенное время." );

				DeletePVar( i, "Contract:Used" );
			}

			Player[i][uWhoreTimeEnd]--;
			new tmin, tsec;
			gmtime( Player[i][uWhoreTimeEnd], _, _, _, _, tmin, tsec );
			format:g_string( "~n~~n~~n~~n~~n~~n~~n~~n~~n~~w~%02d:%02d", tmin, tsec );
			GameTextForPlayer( i, g_string, 3000, 3 );
		} `
		
`function RespawnWhore( i )
{
	FCNPC_RemoveFromVehicle( CrimeWhore[i][ w_npc ] );
	FCNPC_SetPosition( CrimeWhore[i][ w_npc ], CrimeWhore[i][w_pos][0], CrimeWhore[i][w_pos][1], CrimeWhore[i][w_pos][2] );
	FCNPC_SetAngle( CrimeWhore[i][ w_npc ], CrimeWhore[i][w_pos][3] );

	return 1;
}

stock CreateWhore( i )
{
	if( FCNPC_IsValid( CrimeWhore[i][ w_npc ] ) )
		FCNPC_Destroy( CrimeWhore[i][ w_npc ] );

	CrimeWhore[i][ w_id ] = i;
	CrimeWhore[i][ w_skin ] = GetWhoreRandomSkin();
	CrimeWhore[i][ w_in_progress ] = false;

	format:g_small_string("NPC_WHORE_%d", i);
	CrimeWhore[i][ w_npc ] = FCNPC_Create(g_small_string);

	CrimeWhore[i][w_pos][0] = WhorePositions[i][0];
	CrimeWhore[i][w_pos][1] = WhorePositions[i][1];
	CrimeWhore[i][w_pos][2] = WhorePositions[i][2];
	CrimeWhore[i][w_pos][3] = WhorePositions[i][3];

	FCNPC_Spawn( CrimeWhore[i][ w_npc ], CrimeWhore[i][ w_skin ], CrimeWhore[i][w_pos][0], CrimeWhore[i][w_pos][1], CrimeWhore[i][w_pos][2] );
	FCNPC_SetAngle( CrimeWhore[i][ w_npc ], CrimeWhore[i][w_pos][3] );

	FCNPC_SetInvulnerable( CrimeWhore[i][ w_npc ], true );
	FCNPC_SetVirtualWorld( CrimeWhore[i][ w_npc ], 1 );

	CrimeWhore[i][w_area] = CreateDynamicSphere( CrimeWhore[i][w_pos][0], CrimeWhore[i][w_pos][1], CrimeWhore[i][w_pos][2], 5.0, 0, 0 );
}`

Here is the code where FSNPC is used

**Comment by itslapsu** [comment]
> > Here is the code that is used by FСNPС, but while the server is crashing they are not used.
> 
> Try to use callback for the code which should be executed after the NPC creation.`FCNPC_OnCreate`

I mean, the server starts up, the bots work. Then after a while, even when there is no interaction with the bots, the server crashes.

**Comment by ziggi** [comment]
> What could cause crashes during GMX?

Using FCNPC_Create inside of OnGameModeInit, use FCNPC_OnInit instead (https://github.com/ziggi/FCNPC/issues/200)

**Comment by itslapsu** [comment]
> FCNPC_OnInit

Thank you. 

I managed to catch a crash when the crashlog contains a reference to sampvoice.SO, when you left the server and the server has not yet managed to disconnect the player and you log in with the same nickname, a samp window pops up that such a nickname is already in use - the server crashes.

Is there an option to fix this?

**Comment by ziggi** [comment]
> Is there an option to fix this?

I don't know.

**Comment by itslapsu** [comment]
> > Is there an option to fix this?
> 
> I don't know.

I deleted sampvoice, everything became stable, everything is cool, I was happy.

But after a day the server unexpectedly crashed. Again, no NPCs were used, they just stood in place.

```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 18 from 80961fc

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf5ae1b86]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7f57580]
  #2 in ./samp03svr() [0x80961fc]
  #3 in plugins/FCNPC.so(amx_Push+0x29) [0xf5b0beb9]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.11

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5e00
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81ab8ec
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```

**Comment by itslapsu** [comment]
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is ed8ea086 from ed8ea086

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf5ae1b86]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7f16580]
  #2 in [0xed8ea086]
  #3 in ./samp03svr() [0x808106e]
  #4 in ./samp03svr() [0x8073680]
  #5 in ./samp03svr() [0x808ec9d]
  #6 in ./samp03svr() [0x8074846]
  #7 in ./samp03svr() [0x80763fe]
  #8 in /lib/i386-linux-gnu/libc.so.6(+0x8836d) [0xf7a1436d]
  #9 in /lib/i386-linux-gnu/libc.so.6(clone+0x66) [0xf7aad436]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2
  FCNPC: 2.0.11

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5e00
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81ab8ec
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```

After 10 minutes, crash again.
