### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Su37Erich** [ziggi/FCNPC#80]
Somehow the server crashes after more than 3 zombies start following and fighting you, the log:
`FCNPC_MeleeAttack(npcid);
					FCNPC_GoToPlayer(npcid, i);`

```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 2ba9 from f54fe66a

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf54f9fd6]
  #1 in [0xf77c6d50]
  #2 in plugins/FCNPC.so(_ZN11CPlayerData8GetStateEv+0xa) [0xf54fe66a]
  #3 in plugins/FCNPC.so(_ZN11CPlayerData11GetPositionEP7CVector+0x22) [0xf55001f2]
  #4 in plugins/FCNPC.so(_ZN11CPlayerData16UpdateMovingDataE7CVectorfbff+0x5a) [0xf5500b8a]
  #5 in plugins/FCNPC.so(_ZN11CPlayerData7ProcessEv+0x892) [0xf55037b2]
  #6 in plugins/FCNPC.so(_ZN14CPlayerManager7ProcessEv+0x39) [0xf5504449]
  #7 in plugins/FCNPC.so(_ZN7CServer7ProcessEv+0x4f) [0xf5506c1f]
  #8 in plugins/FCNPC.so(ProcessTick+0x23) [0xf5508153]
  #9 in ./samp03svr() [0x80d1ce2]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.7.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
