### ISSUE TITLE
Crashing when bot kill player

### ISSUE THREAD

**Issue by blackaslan** [ziggi/FCNPC#85]
The server crash when a bot kill a player

```
========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 6c6c694d from b7492508

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0xdc) [0xb53342ec]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xb7779600]
  #2 in /lib32/libc.so.6(_IO_vfprintf+0x2278) [0xb7492508]
  #3 in /lib32/libc.so.6(vsprintf+0x92) [0xb74b27a2]
  #4 in /root/samp03/samp03svr() [0x80ad731]
  #5 in /root/samp03/samp03svr() [0x80d99e9]
  #6 in /root/samp03/samp03svr() [0x80950e4]
  #7 in plugins/crashdetect.so(_ZN11CrashDetect13DoAmxCallbackEiPiS0_+0x49b) [0xb742594b]
  #8 in plugins/crashdetect.so(+0x1b8f8) [0xb74288f8]
  #9 in plugins/crashdetect.so(amx_Exec+0x18e6) [0xb742c916]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.7.3

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```

```Pawn
public FCNPC_OnGiveDamage(npcid, damagedid, weaponid, bodypart, Float:health_loss)
{
	if(IsPlayerNPC(damagedid))
		return 1;
	new Float:saludActual;
	GetPlayerHealth(damagedid, saludActual);
	saludActual = saludActual - (health_loss*zNPC_DANIO); 
	SetPlayerHealth(damagedid, saludActual);
	return 1;
}
```

```Pawn
public OnPlayerTakeDamage(playerid, issuerid, Float: amount, weaponid, bodypart)
{
	return 0;
}
```
