### ISSUE TITLE
Exception - 9fb1000 from 9fb0ffe

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#86]
IDK when and how I got this exception:
And couldnt find anything wrong in my **server_log.txt**

```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 9fb1000 from 9fb0ffe

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xe9e95fd6]
  #1 in [0xeb13a410]
  #2 in [0x9fb0ffe]
  #3 in ./samp03svr() [0x80d09e8]
  #4 in ./samp03svr() [0x80b058c]
  #5 in plugins/FCNPC.so(_ZN10CFunctions9NewPlayerEPc+0x1b6) [0xe9e96966]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.7.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```

**Logs:**
[18:59:51] Creating/Spawning NPCs...
[18:59:51] [npc:join] npc0_Security has joined the server (69:127.0.0.1)
[18:59:51] [npc:join] npc1_Security has joined the server (68:127.0.0.1)
[18:59:51] [npc:join] npc2_Security has joined the server (67:127.0.0.1)
[18:59:51] [npc:join] npc3_Worker has joined the server (66:127.0.0.1)
[18:59:51] [npc:join] npc4_Security has joined the server (65:127.0.0.1)
[18:59:51] [npc:join] npc5_Security has joined the server (64:127.0.0.1)
[18:59:51] [npc:join] npc6_Army has joined the server (63:127.0.0.1)
[18:59:51] [npc:join] npc7_Army has joined the server (62:127.0.0.1)
[18:59:51] [npc:join] npc8_Police has joined the server (61:127.0.0.1)
[18:59:51] [npc:join] npc9_Agent has joined the server (60:127.0.0.1)
[18:59:51] [npc:join] npc10_Agent has joined the server (59:127.0.0.1)
