### ISSUE TITLE
Server crash while player disconnect

### ISSUE THREAD

**Issue by Abyss-z94** [ziggi/FCNPC#91]
My server alway crash when player disconnect from server, idk why that working perfect before upgrade to 1.7.2
```
=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 6566667b from f7441fa6

Backtrace:
  #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x116) [0xf5908346]
  #1 in [0xf774e410]
  #2 in /lib/libc.so.6(_IO_vfprintf+0x3d66) [0xf7441fa6]
  #3 in /lib/libc.so.6(vsprintf+0x92) [0xf7461212]
  #4 in ./samp03svr() [0x80ad731]
  #5 in ./samp03svr() [0x80d99e9]
  #6 in ./samp03svr() [0x80950e4]
  #7 in plugins/sampp_server.so(+0x295ed) [0xf58845ed]
  #8 in [0xe9]

Information:
  System: GNU/Linux
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.7.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
  FUNC_CPlayer__Kill: 0x80cb220
  FUNC_CPlayer__EnterVehicle: 0x80cc1c0
  FUNC_CPlayer__ExitVehicle: 0x80cc340
  FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
  FUNC_GetVehicleModelInfo: 0x80d5d30
  FUNC_CConsole__GetIntVariable: 0x80a0070
  FUNC_ClientJoin_RPC: 0x80b0030

Pointers:
  VAR_ServerAuthentication: 0x81aa8a8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================
```
